# Generated by Django 3.1.5 on 2021-08-04 10:22

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='blog_images/default_blog_img.png', upload_to='blog_images', verbose_name='Bloq başlıq şəkli')),
                ('title', models.CharField(default='', max_length=250, verbose_name='Bloq başlığı')),
                ('context', ckeditor.fields.RichTextField(default='', verbose_name='Bloq məzmunu')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('views_time', models.PositiveBigIntegerField(default=0, verbose_name='Baxış sayı')),
                ('comment_number', models.PositiveBigIntegerField(default=0, verbose_name='Rəy sayı')),
                ('like_number', models.PositiveBigIntegerField(default=0, verbose_name='Bəyənmə sayı')),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='title', unique=True)),
            ],
            options={
                'verbose_name': 'Bloq',
                'verbose_name_plural': 'Bloqlar',
                'db_table': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kateqoriya')),
            ],
            options={
                'verbose_name': 'Kateqoriya',
                'verbose_name_plural': 'Kateqoriyalar',
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Rəy')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogs.blogmodel', verbose_name='Bloq')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blogs.commentmodel', verbose_name='Əsas rəy')),
            ],
            options={
                'verbose_name': 'Rəy',
                'verbose_name_plural': 'Rəylər',
                'db_table': 'Comments',
            },
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='categories',
            field=models.ManyToManyField(related_name='blogs', to='blogs.CategoryModel', verbose_name='Kateqoriyalar'),
        ),
    ]
