# Generated by Django 3.1.5 on 2021-08-04 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='writer',
            field=models.CharField(default='', max_length=100, verbose_name='Yazan'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='comment_number',
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name='Rəy sayı'),
        ),
    ]
